/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author numa114
 */

import civitas_p1.CivitasJuego;
import java.util.ArrayList;
import civitas_p1.Jugador;
import civitas_p1.OperacionesJuego;
import civitas_p1.SalidasCarcel;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel; 




public class CivitasView extends javax.swing.JFrame {

    CivitasJuego juego;
    JugadorPanel jugadorPanel;
    
    
    void setCivitasJuego(CivitasJuego game){
        juego = game;
        setVisible(true); 
    }
    
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        jugadorPanel = new JugadorPanel();
        contenedorVistaJugador.add(jugadorPanel);
        
        
        
        
        repaint();
        revalidate();
    }

    void actualizarVista(){
        
        jugadorPanel.setJugador(juego.getJugadorActual());
        
        jugadorPanel.setVisible(true);
        
        
        Ranking.setVisible(false);
        ranking.setVisible(false);
        
        if(juego.finalDelJuego()){
            
            ArrayList<Jugador>rank=juego.ranking();   //preguntar duda
            String r = "";
            for(int i=0; i<rank.size(); i++)
                r= r + rank.get(i).toString() + "\n";
            
            Ranking.setText(r);
            Ranking.setVisible(true);
            ranking.setVisible(true);
            
        }
        
        repaint();
        revalidate();
        
        
    }
    
    void mostrarSiguienteOperacion(OperacionesJuego operacion){
        
        SiguienteOperacion.setText(operacion.toString());
        SiguienteOperacion.setVisible(true);
        actualizarVista();
        
    }
    
    void mostrarEventos(){
        
        //crea la ventana del diario
        DiarioDialog diarioD = new DiarioDialog(this);
        
    }
    
    Respuestas comprar(){
        
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea comprar la calle actual?", "COMPRAR", JOptionPane.YES_NO_OPTION);
        return (Respuestas.values()[opcion]);
        
    }
    
    GestionarDialog gestionarD = new GestionarDialog(this);
    
    int getGestion(){
        return gestionarD.getGestion();
    }
    
    int getPropiedad(){
        
        return gestionarD.getPropiedad();
    }
    
    
    public void gestionar(){
        
        gestionarD.gestionar(juego.getJugadorActual());
        gestionarD.pack();
        gestionarD.repaint();
        gestionarD.revalidate();
        gestionarD.setVisible(true);
        
    }
    
    SalidasCarcel salirCarcel(){
        
        String[]opciones = {"Pagando", "Tirando"};
        
        int respuesta = JOptionPane.showOptionDialog(null, "¿Como quiere salir de la carcel?", "SALIR DE LA CARCEL",JOptionPane.DEFAULT_OPTION,
                                                        JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);
        
        return (SalidasCarcel.values()[respuesta]);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorVistaJugador = new javax.swing.JPanel();
        ranking = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ranking = new javax.swing.JTextArea();
        CasillaActual = new javax.swing.JPanel();
        SiguienteOperacion = new javax.swing.JTextField();
        siguienteOperacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ranking.setText("Ranking");
        ranking.setEnabled(false);

        Ranking.setColumns(20);
        Ranking.setRows(5);
        Ranking.setEnabled(false);
        jScrollPane1.setViewportView(Ranking);

        CasillaActual.setEnabled(false);

        javax.swing.GroupLayout CasillaActualLayout = new javax.swing.GroupLayout(CasillaActual);
        CasillaActual.setLayout(CasillaActualLayout);
        CasillaActualLayout.setHorizontalGroup(
            CasillaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        CasillaActualLayout.setVerticalGroup(
            CasillaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        SiguienteOperacion.setEnabled(false);

        siguienteOperacion.setText("Siguiente Operación");
        siguienteOperacion.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(siguienteOperacion)
                        .addGap(18, 18, 18)
                        .addComponent(SiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256)
                        .addComponent(CasillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ranking))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(siguienteOperacion)
                                    .addComponent(SiguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ranking))
                            .addComponent(CasillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CasillaActual;
    private javax.swing.JTextArea Ranking;
    private javax.swing.JTextField SiguienteOperacion;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ranking;
    private javax.swing.JLabel siguienteOperacion;
    // End of variables declaration//GEN-END:variables

    
}
