/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas_p1.TituloPropiedad;
import java.util.ArrayList;


public class PropiedadPanel extends javax.swing.JPanel {

    TituloPropiedad titulopropiedad;
    
    void setPropiedad(TituloPropiedad titulo){
        
        titulopropiedad = titulo;
        Nombre.setText(titulo.getNombre());
        NumeroCasas.setText(Integer.toString(titulo.getNumCasas()));
        NumeroHoteles.setText(Integer.toString(titulo.getNumHoteles()));
        Hipotecada.setText(Boolean.toString(titulo.getHipotecado()));
        PrecioCompra.setText(Float.toString(titulo.getPrecioCompra()));
        PrecioEdificar.setText(Float.toString(titulo.getPrecioEdificar()));
        Alquiler.setText(Float.toString(titulo.getPrecioAlquiler()));
        PrecioVenta.setText(Float.toString(titulo.getPrecioVenta()));
        PrecioHipoteca.setText(Float.toString(titulo.getImporteHipoteca()));
        
    }
    
    
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        numeroCasas = new javax.swing.JLabel();
        hipotecada = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        NumeroCasas = new javax.swing.JTextField();
        NumeroHoteles = new javax.swing.JTextField();
        Hipotecada = new javax.swing.JTextField();
        numeroHoteles = new javax.swing.JLabel();
        precioCompra = new javax.swing.JLabel();
        precioEdificar = new javax.swing.JLabel();
        alquiler = new javax.swing.JLabel();
        precioVenta = new javax.swing.JLabel();
        precioHipoteca = new javax.swing.JLabel();
        PrecioCompra = new javax.swing.JTextField();
        PrecioEdificar = new javax.swing.JTextField();
        Alquiler = new javax.swing.JTextField();
        PrecioVenta = new javax.swing.JTextField();
        PrecioHipoteca = new javax.swing.JTextField();

        titulo.setText("Vista Propiedad");
        titulo.setEnabled(false);

        nombre.setText("Nombre:");
        nombre.setEnabled(false);

        numeroCasas.setText("Numero de casas:");
        numeroCasas.setEnabled(false);

        hipotecada.setText("¿Hipotecada?:");
        hipotecada.setEnabled(false);

        Nombre.setEnabled(false);
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        NumeroCasas.setEnabled(false);
        NumeroCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroCasasActionPerformed(evt);
            }
        });

        NumeroHoteles.setEnabled(false);

        Hipotecada.setEnabled(false);
        Hipotecada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HipotecadaActionPerformed(evt);
            }
        });

        numeroHoteles.setText("Numero de hoteles:");
        numeroHoteles.setEnabled(false);

        precioCompra.setText("Precio de compra:");
        precioCompra.setEnabled(false);

        precioEdificar.setText("Precio de edificación:");
        precioEdificar.setEnabled(false);

        alquiler.setText("Precio de alquiler:");
        alquiler.setEnabled(false);

        precioVenta.setText("Precio de venta:");
        precioVenta.setEnabled(false);

        precioHipoteca.setText("Precio de hipoteca:");
        precioHipoteca.setEnabled(false);

        PrecioCompra.setEnabled(false);

        PrecioEdificar.setEnabled(false);
        PrecioEdificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioEdificarActionPerformed(evt);
            }
        });

        Alquiler.setEnabled(false);

        PrecioVenta.setEnabled(false);
        PrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioVentaActionPerformed(evt);
            }
        });

        PrecioHipoteca.setEnabled(false);
        PrecioHipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioHipotecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombre)
                        .addGap(18, 18, 18)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numeroHoteles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumeroHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(precioCompra)
                        .addGap(18, 18, 18)
                        .addComponent(PrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hipotecada)
                        .addGap(18, 18, 18)
                        .addComponent(Hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(precioEdificar)
                        .addGap(18, 18, 18)
                        .addComponent(PrecioEdificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alquiler)
                        .addGap(18, 18, 18)
                        .addComponent(Alquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(precioVenta)
                        .addGap(18, 18, 18)
                        .addComponent(PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(precioHipoteca)
                        .addGap(18, 18, 18)
                        .addComponent(PrecioHipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(titulo)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(numeroCasas)
                            .addGap(18, 18, 18)
                            .addComponent(NumeroCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumeroCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroCasas))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(NumeroHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroHoteles)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hipotecada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrecioEdificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioEdificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alquiler))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrecioHipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioHipoteca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titulo.getAccessibleContext().setAccessibleName("nombre titulo");
        nombre.getAccessibleContext().setAccessibleName("numero casas");
        numeroCasas.getAccessibleContext().setAccessibleName("numero hoteles");
    }// </editor-fold>//GEN-END:initComponents

    private void HipotecadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HipotecadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HipotecadaActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void NumeroCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCasasActionPerformed

    private void PrecioEdificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioEdificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioEdificarActionPerformed

    private void PrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioVentaActionPerformed

    private void PrecioHipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioHipotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioHipotecaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alquiler;
    private javax.swing.JTextField Hipotecada;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField NumeroCasas;
    private javax.swing.JTextField NumeroHoteles;
    private javax.swing.JTextField PrecioCompra;
    private javax.swing.JTextField PrecioEdificar;
    private javax.swing.JTextField PrecioHipoteca;
    private javax.swing.JTextField PrecioVenta;
    private javax.swing.JLabel alquiler;
    private javax.swing.JLabel hipotecada;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel numeroCasas;
    private javax.swing.JLabel numeroHoteles;
    private javax.swing.JLabel precioCompra;
    private javax.swing.JLabel precioEdificar;
    private javax.swing.JLabel precioHipoteca;
    private javax.swing.JLabel precioVenta;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
